version: "3.9"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    container_name: clickhouse
    environment:
      - CLICKHOUSE_DB=anticheat
      - CLICKHOUSE_USER=app
      - CLICKHOUSE_PASSWORD=app
    volumes:
      - ./clickhouse-init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ch_data:/var/lib/clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  ingest:
    build: ../ingest-go
    depends_on:
      - clickhouse
    environment:
      - CH_HTTP=http://clickhouse:8123
      - CH_DB=anticheat
      - CH_USER=app
      - CH_PASS=app
    ports:
      - "8080:8080"


volumes:
  ch_data: {}
